# Generated by Django 5.1.4 on 2025-01-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('e_mail', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(max_length=11)),
            ],
        ),
    ]
